name: Home Assistant
version: 1.0.1
bundle_id: com.homeassistant.home-assistant.homeassistant
app_info: app_info.md
hos_version: 2023.1.4
config_version: 1.0.0
docker_config:
    image_name: homeassistant/home-assistant
    tag: 2024.5
    container_name: Home Assistant
    network_mode: host
    icon: icon.png
    web_ui_port: "8123"
    ports:
        - network_protocol: tcp
          container: "8123"
          host: "8123"
    volumes:
        - container: /dev
          host: /dev
        - container: /run/dbus
          host: /run/dbus
        - container: /config
          host: /var/hass/config
        - container: /var/run/dbus
          host: /var/run/dbus
    env_variables:
      - name: TZ
        value: Asia/Shanghai
    devices: []
    command: []
    privileged_mode: true
    restart_policy: unless-stopped
    resources_limit: false
    entrypoint: /bin/sh
    maximum_cpu_usage: ""
    memory_limit: ""
    container_hostname: homeassistant
hdp_update_info: ""
init_script: ""
uninstall: ""
resource_files:
author: houzzkit-team
author_introduction_url: "https://www.houzzkit.com"
create_time: 1710987790
update_author_introduction_url: spike
hdp_create_time: 1710987790
